version: '2.1'
services:
  jobmanager:
    build: processor
    volumes:
      - ./processor:/opt/processor
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  ingestor:
    build: ingestor
    stdin_open: true
    tty: true
    depends_on:
      - kafka
  taskmanager:
    build: processor
    volumes:
    - ./processor:/opt/processor
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "binance-feed:1:1"

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka


#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.8.0
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#  load-kibana-dashboard:
#    build: ./kibana
#    command: ['/bin/bash', '-c', 'cat /tmp/load/load_ndjson.sh | tr -d "\r" | bash']
#    depends_on:
#      - kibana
